import com.android.build.api.variant.FilterConfiguration

plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'androidx.navigation.safeargs.kotlin'
}


 def localProperties = new Properties()
 def localFile = rootProject.file('local.properties')
 if (localFile.exists()) {
     localFile.withInputStream { stream -> localProperties.load(stream) }
 }


android {

    compileSdkVersion 35
    buildFeatures {
        buildConfig true
        viewBinding true
    }

    namespace 'com.cookiejarapps.android.smartcookieweb'

    defaultConfig {
        applicationId "ua.kiev.intersystems.edpro.warranty"
        minSdkVersion 21
        targetSdkVersion 35
        // Increment by 4 with each update
        versionCode 128
        versionName "29.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "SITE_URL",
                "\"https://equipify.com.ua/index.php/servis-ta-garantiya\""
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17
    }


    signingConfigs {
        create("release") {
            storeFile = file(localProperties.getProperty("RELEASE_STORE_FILE"))
            storePassword = localProperties.getProperty("RELEASE_STORE_PASSWORD")
            keyAlias = localProperties.getProperty("RELEASE_KEY_ALIAS")
            keyPassword = localProperties.getProperty("RELEASE_KEY_PASSWORD")
            enableV1Signing = true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "abi"

    splits {
        abi {
            enable true
            reset()

            include "arm64-v8a", "x86_64"

            universalApk false
        }
    }

    androidResources {
        noCompress += 'ja'
    }

    lint {
        abortOnError false
    }
}

def abiBaseMap = [
        "arm64-v8a"  : 1,
        "x86_64"     : 2
]

androidComponents {
    onVariants(selector().all()) { variant ->
        variant.outputs.each { output ->
            def abi = output.getFilters()
                    .find { it.filterType == FilterConfiguration.FilterType.ABI }
                    ?.identifier

            if (abi != null) {
                def base = abiBaseMap[abi] ?: 0
                def orig = output.versionCode.get()
                output.versionCode.set(base * 1000 + orig)
            }
        }
    }
}


dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation "androidx.annotation:annotation:1.9.1"
    implementation "androidx.appcompat:appcompat:1.7.1"
    implementation 'androidx.navigation:navigation-fragment-ktx:2.9.0'
    implementation 'androidx.navigation:navigation-ui-ktx:2.9.0'

    final def mozComponentsVersion = "140.0"

    implementation "org.mozilla.components:concept-engine:$mozComponentsVersion"
    implementation "org.mozilla.components:concept-base:$mozComponentsVersion"

    implementation "org.mozilla.components:browser-engine-gecko:$mozComponentsVersion"
    implementation "org.mozilla.components:browser-state:$mozComponentsVersion"
    implementation "org.mozilla.components:browser-errorpages:$mozComponentsVersion"

    implementation "org.mozilla.components:feature-tabs:$mozComponentsVersion"
    implementation "org.mozilla.components:feature-session:$mozComponentsVersion"
    implementation "org.mozilla.components:feature-intent:$mozComponentsVersion"
    implementation "org.mozilla.components:feature-contextmenu:$mozComponentsVersion"
    implementation "org.mozilla.components:feature-app-links:$mozComponentsVersion"
    implementation "org.mozilla.components:feature-prompts:$mozComponentsVersion"
    implementation "org.mozilla.components:feature-sitepermissions:$mozComponentsVersion"
    implementation "org.mozilla.components:feature-webcompat:$mozComponentsVersion"

    implementation "org.mozilla.components:support-base:$mozComponentsVersion"
    implementation "org.mozilla.components:support-utils:$mozComponentsVersion"
    implementation "org.mozilla.components:support-ktx:$mozComponentsVersion"

    implementation "org.mozilla.components:ui-colors:$mozComponentsVersion"
    implementation "org.mozilla.components:ui-widgets:$mozComponentsVersion"

    implementation "org.mozilla.components:lib-state:$mozComponentsVersion"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}

project.configurations.configureEach {
    resolutionStrategy.capabilitiesResolution.withCapability("org.mozilla.telemetry:glean-native") {
        def toBeSelected = candidates.find { it.id instanceof ModuleComponentIdentifier && it.id.module.contains('geckoview') }
        if (toBeSelected != null) {
            select(toBeSelected)
        }
        because 'use GeckoView Glean instead of standalone Glean'
    }
}